### ISSUE TITLE
README update?

### ISSUE THREAD

**Issue by lurch** [resin-io-modules/pipage#4]
According to https://github.com/resin-io-modules/pipage/tree/master/doc#Pipeline+splice `pipe.splice` "Splice streams into or out of the pipeline"

Does that mean that the top-level README could replace the `pipeline.splice` and `pipeline.append` with just a single `pipeline.splice`?

Alternatively, I wonder if the API would be clearer if `splice` was deprecated and replaced with separate `remove(index, count)` and `insert(index, ...streams)`? And maybe `pipeline.remove(pipeline.indexOf(someStream), 1)` would be so commonplace that it should also have a dedicated method?

**Comment by jhermsmeier** [comment]
> Does that mean that the top-level README could replace the `pipeline.splice` and `pipeline.append` with just a single `pipeline.splice`?

Yup, I just stuck it in there to showcase it's usage, the README really does need an overhaul.

> Alternatively, I wonder if the API would be clearer if splice was deprecated

I would argue against removal of `.splice()` as it handles all internal connections between streams, and also sports the same API as the native `Array.prototype.splice()`, so I think it's pretty handy to have around, even if not used frequently.

> replaced with separate `remove(index, count)` and `insert(index, ...streams)`?

That's just `.splice(index, removeCount)`, but I added `.remove(stream)` as a shorter `.splice(pipeline.indexOf(someStream), 1)` in the referenced PR #6, as well as `insert(index, ...streams)`, if that makes sense?

**Comment by lurch** [comment]
> and also sports the same API as the native Array.prototype.splice()

Ahh, there's me showing my lack of JS knowledge again ;-)
If it's emulating some other common usage-pattern then that makes sense, but looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype does that mean some of the existing methods you're using should be renamed? e.g. `prepend` -> `unshift`, `append` -> `push`, etc.

Again, please excuse my naivete if that doesn't make sense!

> the README really does need an overhaul

It would be useful for the top-level README to have a link to the docs, at least ;)

**Comment by jhermsmeier** [comment]
> does that mean some of the existing methods you're using should be renamed? e.g. prepend -> unshift, append -> push, etc.

Yeah, I thought about that as well at first, but then quickly remembered that `.unshift()` and `.push()` are also methods used by streams to [push](https://nodejs.org/api/stream.html#stream_readable_push_chunk_encoding) / [unshift](https://nodejs.org/api/stream.html#stream_readable_unshift_chunk) chunks into or out of the internal buffer governed by the `highWaterMark` – and since the Pipeline is a duplex stream, I didn't want to have the possibility of overriding those methods interfering with backpressure handling and such when the Pipeline is being piped to, or being piped into a writable receiver.

Should probably also mention the reasoning behind this in the README

> It would be useful for the top-level README to have a link to the docs, at least ;)

Oh yes, indeed!

**Comment by lurch** [comment]
Ah, I hadn't considered method-name collision.
It'd be a bit yucky, but I guess one workaround would be to prefix all the 'pipeline manipulation' method names with a specific prefix, to differentiate them from the regular stream methods, and then you could have something like `pl_push`, `pl_pop`, `pl_unshift`, `pl_slice` etc. But that's probably no better than your current solution :-/

**Comment by lurch** [comment]
Most of the questions here have already been addressed in other PRs, except for:
> the README really does need an overhaul.

;-)
