### ISSUE TITLE
"T-junctions" ?

### ISSUE THREAD

**Issue by lurch** [resin-io-modules/pipage#8]
Given that this module is all about connecting streams into pipelines, would it be worth (would it make sense?) adding something like the equivalent of the Unix `tee` command? (but obviously writing to another stream, rather than always a disk-file)
It might make the testing-multiple-transforms unit-tests easier to write, because you could 'inspect' the contents of the pipeline between each transform?

Only a suggestion, not necessarily a feature request, so feel free to close if it doesn't make sense / wouldn't be possible.

**Comment by jhermsmeier** [comment]
Node streams support piping to multiple targets by default, so you should already be able to do that:

```js
// You could either pipe the pipeline itself to two different streams;
// Note that if you want to pipe the same stream to multiple others,
// you can't chain the `.pipe()`s, as `.pipe()` returns the stream being piped to
pipeline.pipe( inspectionStream )
pipeline.pipe( fs.createWriteStream( '/dev/rdisk2' ) )

// Or, pipe a stream within the pipeline to another stream
pipeline.get( index ).pipe( inspectionStream )
```

Thinking about it, I should also add this to the README

**Comment by lurch** [comment]
Nice :)
Just like you did with `remove`, I wonder if it'd be worth adding a "shortcut method" for `pipeline.get(pipeline.indexOf(someStream)).pipe(inspectionStream)` ?

P.S. Does an error get thrown if you try adding the same stream twice to a pipeline?

**Comment by jhermsmeier** [comment]
> Just like you did with remove, I wonder if it'd be worth adding a "shortcut method" for pipeline.get(pipeline.indexOf(someStream)).pipe(inspectionStream) ?

Well, if you have a reference to the stream already, you can just do `someStream.pipe(inspectionStream)`, no need to get the same stream again from the pipeline ;)

> P.S. Does an error get thrown if you try adding the same stream twice to a pipeline?

No, I thought about adding it for a moment, then realised it might be an unnecessary constraint, as you might even want to be able to do that in some cases (I can't really think of one off the top of my head, but I bet there are some).

Maybe we should add an option to enable or disable that behavior – what do you think?

**Comment by lurch** [comment]
> no need to get the same stream again from the pipeline ;)

Hah, can you tell I've never used streams in NodeJS? ;-)

> as you might even want to be able to do that in some cases

Sounds like a question for @jviotti ;-)

But if we _do_ allow the same stream to be added to a single pipeline multiple times, the docs need to mention "from which end" the `indexOf` method searches. (and there should maybe be an optional `fromIndex` parameter? https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf )

**Comment by jviotti** [comment]
I can't think of any reason why you would want to add the same stream multiple times, but I also can't see a reason why not to support it (I'm sure there might be some weird edge case that would benefit for this), so our `indexOf` should still behave correctly here.

**Comment by jhermsmeier** [comment]
Closing this, as the question has been resolved
